### ISSUE TITLE
Access Admin sur Heroku

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#12]
Salut Tom, 

dis-donc ca caille à Paris comme à Berlin?! Froid affreux, mais je me réchauffe avec de l'amour pour le coding! :-D D'ailleurs il faut qu'on parle un jour du lien entre coding et poésie. J'en vois...

On avance bien sur le front Web Dev! Ici tu verra le résultat du travail avec le designer:  https://secret-eyrie-62057.herokuapp.com/ratings/new 

J'aimerais bien donner accès à mon equipe au backend, rails admin en cliquant sur https://secret-eyrie-62057.herokuapp.com/admin . Mais ca ne marche pas. 

Si je clique sur: http://localhost:3000/admin ca marche (sous condition que je sing in avec admin@ticketee.com et mon password). 

Le problème c'est quand je clique sur https://secret-eyrie-62057.herokuapp.com/users/sign_in et veux "sign-in" avec admin@ticketee.com et mon password, il me dit  "Invalid email or password". Je ne peux donc pas accéder au back-end du site web. J'ai fait "heroku run rake db:migrate", après avoir pushé sur Heroku, mais ca ne change rien. 

T'as une idée de ce qu'il peux s'agir?

Ciao ciao,
Nico

**Comment by thaume** [comment]
Hello Nico,

Oui il fait bien froid à Paris (mais moins qu'à Berlin j'imagine :p). Il a même neigé un peu cet après midi ! Heureusement qu'on a l'amour du coding pour se réchauffer comme tu dis :D

Super ces avancées sur le front :) ça donne envie de refaire un stage ! Haha

Pour créer un compte admin sur le back-office il suffit de lancer `heroku run rake db:seed`. Ça devrait créer le compte par défaut (il faudra modifier le mot de passe ensuite). Source : https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md

Lorsque tu `seed` la DB, ça mets des données par défaut pour que ton site puisse fonctionner (comme ici l'admin user de base). Ça devrait aussi résoudre le bug sur la route `/admin`.

Dis moi si ça fonctionne ;)

Cheers!
Tom

**Comment by thaume** [comment]
J'ai lancé la commande `heroku run rake db:seed`, ça devrait etre bon maintenant :)

**Comment by thaume** [comment]
@NicholasWenzel des nouvelles ?

**Comment by NicholasWenzel** [comment]
Ca à marché avec le seed. Il faut just voire, comment changer le mot de passe, car actuellement on tout le monde peux accéder avec quelque soit le mode de passe. 

Je vais m'en occuper la semaine prochaine

**Comment by thaume** [comment]
@NicholasWenzel let's create a new issue with that problem then :)

The website is looking niiiice ! You did a great job man !
