### ISSUE TITLE
Copying the two IGP.com navigation bars into ruby project

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#2]
Salut Tom, 

je voudrais copier le code pour les 2 navbar sur IGP.com dans mon ruby project (celui en jaune et en blanc au dessus de la page). J'ai access au source code en Symphonie 2, avec lequel on l'avait fait. J'ai aussi accès bien sur avec les developer tools de google chrome. Je ne sais pas, comment achever cette tache dans la manière la plus rapide et efficace. 

Quelle est la meilleure façon de procéder la-dessus? Peux-tu me guide la-dessus? 

Merci,
Nico

**Comment by thaume** [comment]
Hello Nico,

Je pense que le mieux ce serait de récupérer depuis le site Symphony 2. Si tu galères trop, tu peux aussi récupérer depuis la console Google Chrome, mais le mieux c'est de chopper un code source !

Tiens moi au courant !
Tom

**Comment by NicholasWenzel** [comment]
OK, je vais faire.
