### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by thaume** [NicholasWenzel/internsgopro#3]
Hello Nico !

J'ai regardé rapidement ce que tu as commencé à faire sur le site, c'est très cool :)

Attention à l'indentation (c'est très très important), comme ici par exemple : https://github.com/NicholasWenzel/internsgopro/blob/master/app/views/offers/show.html.erb#L1

Il faut vraiment que ton HTML soit niquel, sinon ce sera très dur (pour toi et les autres) à relire.

Cheers,
Tom

**Comment by NicholasWenzel** [comment]
ok
