### ISSUE TITLE
Commit name

### ISSUE THREAD

**Issue by thaume** [NicholasWenzel/internsgopro#4]
Hello Nico,

Encore une petite remarque :

N'hésite pas à raccourcir le nom de tes commits Git :)

Par exemple : 
=> "I added Bootstram, Simple Form, Font Awesome gems, as well as some basic bootstrap styling" (https://github.com/NicholasWenzel/internsgopro/commit/213da27d74e57d287801a286fa29f154b01f4a86). Tu aurais pu découper ce commit en 4 commits (**"Add Bootstrap" + "Add Simple Form" + "Add Font Awesome" + "Add basic bootstrap stylings"**).

=> "Committing EMPLOYER MVC pattern, based on scaffold method" (https://github.com/NicholasWenzel/internsgopro/commit/4cb435187580f1c7322262fa16c40857c5117c36). Tu aurais pu simplement dire **"Add employer ressource"**.

Encore une fois, ce sont plus des remarques de style (ce qui est très très important), je n'ai pas le temps de checker dans la "profondeur", mais je regarde ça vite :)

Good job en tout cas, tu progresses très vite ! Est-ce que tu t'éclates au moins ? :P

Cheers !
Tom

**Comment by NicholasWenzel** [comment]
Ok, noté! 

Haha, oui, je m'éclate bien fort!! Notamment dans le debug. ;-) J'aime bien le travail et avance bien, donc tout est cool. Le défi viendra quand je commencera à galèrer...
