### ISSUE TITLE
How to have view all internship offers in one page 

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#6]
Salut Tom, 

maintenant, grace à des relations entre database, je peux écrire des offres pour chaque employer et afficher toutes les offres par employer! J'ai pushed le commit, tu verras. 

Maintenant, je voudrais faire en sorte que je peux voire toutes les offres sur une page. Tu peux me guider sur le processus à considerer?

**Comment by thaume** [comment]
Hello @NicholasWenzel ! Super :)

Veux-tu dire :

1/ Afficher toutes les offres de tous les employeurs sur la même page ?

**ou**

2/ Afficher toutes les offres du même employeur sur une seule page ?

**Comment by NicholasWenzel** [comment]
C'était Nr. 1. J'ai trouvé la solution.
