### ISSUE TITLE
Deploying the website

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#7]
Salut Tom, 

je voudrais deployer le site bientôt! 

Je utilise UDMedia.de pour l'espace server (Gsuite pour email), et suis satisfait, mais UdMedia n'ont pas Postgresql, mails uniquement MySQl. Est-ce que tu suggère que je change server pour un qui utilise PostGresql? Si oui, quelle service provider suggère tu pour de l'espace server? 

Merci,
Nico

**Comment by thaume** [comment]
Hello Nico,

Je suggère Heroku :) c'est le meilleur pour que ton application Ruby on Rails tourne tout le temps et soit connectée avec les meilleurs addons (postgresql, redis, sendgrid...)

Au final le prix que tu payes (et c'est gratuit au départ) vaut largement le service rendu ;) 

PS: j'utilise Heroku pour tous mes projets !

**Comment by NicholasWenzel** [comment]
Tu m'as convancu! Tu vois le pouvoir que tu as sur nous?! ;-)

**Comment by thaume** [comment]
Haha top :)
