### ISSUE TITLE
Moving to private repository for GIT

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#8]
Salut Tom, 

nous avons payé une équipe IT pour transformer le nouveau design du review site fait par une user experience designer (tu aimera bien)! 

Je pense qu'il est heure d'utiliser une private repository pour nos échanges. T'es d'accord et quelle suggère tu? Je sais que Bitbucket travaille avec GIT et est gratuit pour 5 users.

**Comment by thaume** [comment]
Je prefère Github (beaucoup mieux pour les communications sur un projet). C'est 7$ par mois avec : users illimtés et repo privés illimités. A toi de voir :)

**Comment by NicholasWenzel** [comment]
Oui, t'as un argument!
