### ISSUE TITLE
Quel est l'effort pour developer un web crawler? 

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#9]
Ayant commencé à rentrer dans la matière du coding, je me rends compte qu'on peux faire plein de choses. J'aimerais bien developer ces idées, pour renforcer notre investment deck et montrer qu'on va faire choses super cool au niveau technique. 

Ma question: 

- Combien de travail c'est de developper des web crawlers? Et est-ce que c'est quelque chose que moi-meme pourrait realiser? 

L'idée c'est de developer un crawler qui puisse chercher des offres de stage sur les pages offre de nos clients, ainsi que sur des job sites, et de les montrer sur notre page automatiquement.

**Comment by thaume** [comment]
Essaye ce projet open source => https://github.com/felipecsl/wombat :)

**Comment by NicholasWenzel** [comment]
Merci!
